name = "glacier"
version = "0.10.0"

licences = ["Apache-2.0"]
description = "Glacier brings incremental interactive unit testing to Gleam. It is meant as a drop-in replacement for Gleeunit and depends and wraps a fork of it."
repository = { type = "github", user = "inoas", repo = "glacier" }
# links = [{ title = "Website", href = "https://gleam.run" }]
internal_modules = [
  "glacier_demo",
  "glacier_demo/*",
]
gleam = "~> 1.0"

[dependencies]
argv = "~> 1.0"
fs = "~> 8.6"
glacier_gleeunit = ">= 0.11.40 and < 2.0.0"
# glacier_gleeunit = { path = "../gleeunit" }
gleam_community_ansi = "~> 1.4"
gleam_community_colour = "~> 1.4"
gleam_stdlib = "~> 0.36 or ~> 1.0"
shellout = "~> 1.6"
simplifile = "~> 1.7"

[dev-dependencies]

[javascript.deno]
allow_net = ["deno.land"]
allow_read = ["./"]
allow_run = ["gleam"]

[documentation]
pages = [
	{ title = "CHANGELOG", path = "changelog.html", source = "CHANGELOG.md" },
	{ title = "IMPROVE_GLEAM", path = "improve_gleam.html", source = "IMPROVE_GLEAM.md" },
	{ title = "LICENSE", path = "license.html", source = "LICENSE" },
]
