name = "glacier"
version = "0.2.0"

licences = ["Apache-2.0"]
description = "Glacier brings incremental interactive unit testing to Gleam. It is meant as a drop-in replacement for Gleeunit and it relies on it, internally."
repository = { type = "github", user = "inoas", repo = "glacier" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
fs = "~> 8.6"
gleam_stdlib = "~> 0.25"
gleam_erlang = "~> 0.17"
shellout = "~> 1.0"

[dev-dependencies]

[documentation]
pages = [
	{ title = "LICENSE", path = "license.html", source = "LICENSE" },
]
