name = "glacier"
version = "0.6.0"

licences = ["Apache-2.0"]
description = "Glacier brings incremental interactive unit testing to Gleam. It is meant as a drop-in replacement for Gleeunit and depends and wraps a fork of it."
repository = { type = "github", user = "inoas", repo = "glacier" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
fs = "~> 8.6"
gleam_stdlib = "~> 0.25"
gleam_erlang = "~> 0.17"
shellout = "~> 1.0"
glacier_gleeunit = "~> 0.10.11"
gleam_community_ansi = "~> 1.1"

[dev-dependencies]

[javascript.deno]
allow_env = true
allow_read = true
allow_run = true

[documentation]
pages = [
	{ title = "CHANGELOG", path = "changelog.html", source = "CHANGELOG.md" },
	{ title = "LICENSE", path = "license.html", source = "LICENSE" },
]
